application: apples2apples
version: 1
runtime: python
api_version: 1

handlers:
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
- url: /.*
  script: main.py

inbound_services:
- channel_presence